# Site settings
title: magodo's blog
description: "A blog about magodo ..."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://magodo.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: magodo
user_title: awesome title
email: wztdyl@sina.com
twitter_username: magodo_
github_username:  magodo
gplus_userid:  112895509816881023874
linkedin_public_url: "兆廷-翁-518733153" # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: magodo
profile_picture: /assets/avatar/avatar.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5

# projects in header index
projects:
    #- name: fluany
    #  url: https://github.com/fluany/fluany

# exclude my node and gem related stuff
exclude: ['package.json', 'src', 'node_modules', '.bundle', 'Gemfile', 'Gemfile.lock']
